---
- hosts: all
  become: true
  roles:
    - jdk

- hosts: all
  become: true
  roles:
    - docker

- hosts: all
  become: true
  roles:
    - prerequis

- hosts: blanc
  become: true
  roles:
    - masters

- hosts: nodes
  become: true
  roles:
    - nodes

