---
- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install packages to allow apt to use a repository over HTTP
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: ['apt-transport-https', 'ca-certificates','curl','software-properties-common']

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
     repo: 'deb [arch=arm64] https://download.docker.com/linux/ubuntu bionic stable'
     state: present

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes
    state: latest
    name: "{{ item }}"
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']
